#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: launch <image-tag>"
  exit 1
fi

for SECRET in wcfc-apps-mongodb wcfc-apps-slack-notifications wcfc-apps-slack-manuals; do
  if ! podman secret exists $SECRET; then
    echo "Please set up Podman secrets before running this pod"
    exit 1
  fi
done

podman rm -f wcfc-manuals
podman run -d --name wcfc-manuals -p 9300:9300 \
  --secret=wcfc-apps-mongodb,type=env,target=MONGODB \
  --secret=wcfc-apps-WCFC_TOKEN,type=env,target=WCFC_TOKEN \
  --secret=wcfc-apps-slack-notifications,type=env,target=SLACK_TOKEN_NOTIFICATIONS \
  --secret=wcfc-apps-slack-manuals,type=env,target=SLACK_TOKEN_MANUALS \
  -v $(pwd)/log:/opt/app/log \
  -v $(pwd)/root:/opt/app/root \
 $1
